### ISSUE TITLE
Make it as a script for Tampermonkey

### ISSUE THREAD

**Issue by Patraskon** [iMAboud/iMSteam#1]
```
// ==/UserScript==

(function() {
    'use strict';

    // Get the game name from the page
    const gameNameElement = document.getElementById("appHubAppName");
    if (!gameNameElement) {
        return;
    }
    const gameName = gameNameElement.textContent.trim();
    const formattedGameName = gameName.toLowerCase().replace(/'/g, '').replace(/_/g, ' ');

    // Create a button to search on Online Fix
    const steamDBSearchLink = `https://online-fix.me/index.php?do=search&subaction=search&story=${formattedGameName}`;
    createButton(steamDBSearchLink, "Online Fix", "Search on Online Fix", "https://i.imgur.com/WAXRAUw.png");

    // Create a button to search on Skidrow
    const site1SearchLink = `https://www.skidrowreloaded.com/?s=${formattedGameName}&x=0&y=0`;
    createButton(site1SearchLink, "Skidrow", "Search on Skidrow", "https://i.imgur.com/sfzB2DE.png");

    // Create a button to search on FitGirl
    const site2SearchLink = `https://fitgirl-repacks.site/?s=${formattedGameName}`;
    createButton(site2SearchLink, "FitGirl", "Search on FitGirl", "https://i.imgur.com/GOFbweI.png");

    // Create a button to search on SteamRIP
    const newSiteSearchLink = `https://steamrip.com/?s=${formattedGameName}`;
    createButton(newSiteSearchLink, "SteamRIP", "Search on SteamRIP", "https://i.imgur.com/tmvOT86.png");

    // Create a button to search on Dodi
    const new1SiteSearchLink = `https://dodi-repacks.site/?s=${formattedGameName}`;
    createButton(new1SiteSearchLink, "Dodi", "Search on Dodi", "https://i.imgur.com/g71t1Ge.png");

    // Create a button to search on Gload
    const new2SiteSearchLink = `https://gload.to/?s=${formattedGameName}`;
    createButton(new2SiteSearchLink, "Gload", "Search on Gload", "https://gload.to/logo.png");

    function createButton(searchLink, buttonText, tooltipText, iconPath) {
        // Create a button next to the game name to display the link
        const linkButton = document.createElement("button");
        linkButton.style.backgroundColor = 'transparent';
        linkButton.style.border = 'none';
        linkButton.style.padding = '0';
        linkButton.style.cursor = 'pointer';

        const img = new Image();
        img.src = iconPath;
        img.alt = buttonText;
        img.style.width = '64px'; // Adjust width as needed
        img.style.height = '32px'; // Adjust height as needed
        img.style.objectFit = 'contain';

        linkButton.appendChild(img);
        linkButton.classList.add("search-button");
        linkButton.title = tooltipText;

        linkButton.onclick = function() {
            // Open the link in a new tab
            GM_openInTab(searchLink, { active: true });
        };

        // Append the button next to the game name
        gameNameElement.parentNode.appendChild(linkButton);
    }
})();
```

**Comment by iMAboud** [comment]
Awesome! 
I did try it and for some reason no icons popping up on steam, so I did a few changes

// ==UserScript==
// @name         Steam Game Search Links
// @namespace    http://tampermonkey.net/
// @version      1.0
// @description  Add search links for games on Steam pages
// @author       Your Name
// @match        https://store.steampowered.com/*
// @grant        GM_addStyle
// ==/UserScript==

(function() {
    'use strict';

    function createButton(searchLink, buttonText, tooltipText, iconPath) {
        const gameNameElement = document.getElementById("appHubAppName");
        if (gameNameElement) {
            const linkButton = document.createElement("a");
            linkButton.href = searchLink;
            linkButton.setAttribute("target", "_blank"); 

            const img = new Image();
            img.src = iconPath;
            img.alt = buttonText;
            img.style.width = '64px'; 
            img.style.height = '32px'; 
            img.style.objectFit = 'contain';

            linkButton.appendChild(img);
            linkButton.title = tooltipText;
            linkButton.style.marginRight = '10px'; 
            gameNameElement.parentNode.appendChild(linkButton);
        }
    }

    const formattedGameName = document.getElementById("appHubAppName").textContent.trim().toLowerCase().replace(/'/g, '').replace(/_/g, ' ');

    const steamDBSearchLink = `https://online-fix.me/index.php?do=search&subaction=search&story=${formattedGameName}`;
    createButton(steamDBSearchLink, "Online Fix", "Search on Online Fix", "https://i.imgur.com/WAXRAUw.png");

    const site1SearchLink = `https://www.skidrowreloaded.com/?s=${formattedGameName}&x=0&y=0`;
    createButton(site1SearchLink, "Skidrow", "Search on Skidrow", "https://i.imgur.com/sfzB2DE.png");

    const site2SearchLink = `https://fitgirl-repacks.site/?s=${formattedGameName}`;
    createButton(site2SearchLink, "FitGirl", "Search on FitGirl", "https://i.imgur.com/GOFbweI.png");

    const newSiteSearchLink = `https://steamrip.com/?s=${formattedGameName}`;
    createButton(newSiteSearchLink, "SteamRIP", "Search on SteamRIP", "https://i.imgur.com/tmvOT86.png");

    const new1SiteSearchLink = `https://dodi-repacks.site/?s=${formattedGameName}`;
    createButton(new1SiteSearchLink, "Dodi", "Search on Dodi", "https://i.imgur.com/g71t1Ge.png");

    const new2SiteSearchLink = `https://gload.to/?s=${formattedGameName}`;
    createButton(new2SiteSearchLink, "Gload", "Search on Gload", "https://gload.to/logo.png");

})();

**Comment by BlackHARD94** [comment]
+

**Comment by iMAboud** [comment]
> +++

I just updated and added tampermonkey support

**Comment by Patraskon** [comment]
Add to greasyfork.org

**Comment by grant** [comment]
Stop mentioning me
