### ISSUE TITLE
Remove SkidrowReloaded as its a known Malware Distributor.

### ISSUE THREAD

**Issue by NightHammer1000** [iMAboud/iMSteam#12]
As said in Title.
Linking or recommending this site is wildly irresponsible and throws a lot of shade on the safety of this project as well.

**Comment by iMAboud** [comment]
Many others including my friends are using SkidrowReloaded for years with no reported malwares, only false alarm by the antivirus which almost all of the pirated sites have, especially Online-fix which requires an exclusion from antivirus for it to work. 

You can disable it from the settings if you don't trust it though.

**Comment by NightHammer1000** [comment]
I see. 
No, thanks. 
I'd rather not use Software that links to shady sites like that.
